### ISSUE TITLE
Swift 2.0 compability

### ISSUE THREAD

**Issue by natalia-osa** [rhodgkins/RDHCollectionViewTableLayout#1]
Is there any option to support Swift 2.0? Current version doesn't run with Swift 2.0.

Btw: Also maybe you add Carthage support?

**Comment by rhodgkins** [comment]
Hi,

I shall update and add Carthage support tonight :)

Cheers,

Rich

**Comment by rhodgkins** [comment]
Hi Natalia,

Carthage support added - initial version is 1.0.1
There is also a `swift-2.0` branch too :)

Please let me know if you find any issues etc. as I still need to write tests!

Cheers,

Rich
